###Get All Users
GET http://localhost:3000/api/users

###Get User by Id
GET http://localhost:3000/api/users/62ef8f65caca05148c9f9f31

###Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{     
        "username": "Test4",
        "email": "Test4@test.com"
}

###Update User
PATCH http://localhost:3000/api/users/62e91e30f3a93b2ad9042049
Content-Type: application/json

{     
        "username": "JohnSmithSmithSmith",
        "email": "johnsmith@testtest.com"
}
 
###Delete User
DELETE http://localhost:3000/api/users/62ea44977a5e5f66898d4f75


###Get All Thoughts

GET http://localhost:3000/api/thoughts

### Create a Thought

POST http://localhost:3000/api/thoughts
Content-Type: application/json

{     
        "thoughtText": "This is a test thought",
        "user_Id": "62ea44977a5e5f66898d4f75",
        "username": "ChrisChris"
}

### Update a Thought
PUT http://localhost:3000/api/thoughts/62ef9592aceffbe26e2d5e09
Content-Type: application/json

{     
        "thoughtText": "This is a revised test thought",
        "user_Id": "62ea44977a5e5f66898d4f75",
        "username": "ChrisChris"
}

### delete a thought

DELETE http://localhost:3000/api/thoughts/62ef9592aceffbe26e2d5e09


### Create a reaction
PATCH http://localhost:3000/api/thoughts/62ef9bac78a73e8cfe375fe8/reactions
Content-Type: application/json

        {
                "reactionBody": "This is a test reaction",
                "username": "Test3"
        }


### create a duff route

Get http://localhost:3000/api/duff
